name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
      - name: Download dependencies
        run: make deps
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Start local blockchain
        run: |
          anvil --host 0.0.0.0 &
          sleep 5
          # Verify anvil is running
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
            http://localhost:8545 | grep -q "result"
      - uses: browser-actions/setup-chrome@v2
      - name: Format check
        run: |
          make fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted. Please run 'make fmt'"
            git status --porcelain
            exit 1
          fi

      - name: Run tests
        run: make generate && make test

      - name: Run build
        run: make build

      - name: Verify build artifacts
        run: |
          ls -la bin/
          file bin/launchpad-mcp

      - name: Test binary execution
        run: |
          timeout 5s ./bin/launchpad-mcp || [ $? -eq 124 ]
