name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          check-latest: true
      - uses: oven-sh/setup-bun@v2
      - name: Download dependencies
        run: make deps
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Start local blockchain
        run: |
          anvil --host 0.0.0.0 &
          sleep 5
          # Verify anvil is running
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
            http://localhost:8545 | grep -q "result"
      - uses: browser-actions/setup-chrome@v2
      - name: Format check
        run: |
          make fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted. Please run 'make fmt'"
            git status --porcelain
            exit 1
          fi
      - name: Install dependencies
        run: make deps && make generate

      - name: Run build
        run: make build-frontend && make build

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Verify build artifacts
        run: |
          ls -la bin/
          file bin/launchpad-mcp

      - name: Test binary execution
        run: |
          timeout 5s ./bin/launchpad-mcp || [ $? -eq 124 ]

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Docker image (test only)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          build-args: |
            VERSION=latest
            COMMIT_HASH=${{ github.sha }}
            BUILD_TIME=${{ github.run_started_at }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
